### ISSUE TITLE
Error: duplicate 'row.names' are not allowed

### ISSUE THREAD

**Issue by PostoenkoVI** [Nesvilab/FragPipe-Analyst-doc#20]
Hello Fragpipe team!

I was trying to analyze recent LFQ benchmark dataset with FragPipe (LFQ-MBR workflow, DDA mode) and FragPipe Analyst as a follow up for quantitation using https://fragpipe-analyst.org/. I simply took my combined_proteins.tsv and experiment_annotation.tsv files from FragPipe output and uploaded to the website which followed to "Error: duplicate 'row.names' are not allowed".
![fragpipe_analyst_out](https://github.com/Nesvilab/FragPipe-Analyst/assets/78644023/29841df0-b64a-4741-80ff-dc72322e9484)

I'm new to fragpipe, so I was unable to locate an error in my fragpipe analyst input formating. I'm uploading an archive with my combined_proteins.tsv and experiment_annotation.tsv files.
Any help would be useful.

Version info:
FragPipe version 21.1
MSFragger version 4.0
IonQuant version 1.10.12
Philosopher version 5.1.0
[FragPipe_output.zip](https://github.com/Nesvilab/FragPipe-Analyst/files/14177804/FragPipe_output.zip)

Thanks in advance!

**Comment by hsiaoyi0504** [comment]
Thanks for the feedback. @PostoenkoVI The key thing and the error message is that you have the same values for the "sample" column in the experiment_annotation.tsv. It should be unique. If multiple samples have only one corresponding quantification column in the quantification report, you should edit the experiment_annotation.tsv to match that. It happens when the files are assigned to the same experiment during performing FragPipe data processing.
