### ISSUE TITLE
https://fragpipe-analyst.org certificate invalid

### ISSUE THREAD

**Issue by grandrea** [Nesvilab/FragPipe-Analyst-doc#9]
Hello, I can't access the website from my organisation because the website does not have a certificate, or the certificate is expired.

**Comment by hsiaoyi0504** [comment]
@grandrea Can you try http://fragpipe-analyst.nesvilab.org/? It looks like the production server is down for some reason.

**Comment by grandrea** [comment]
this works, thank you

**Comment by pansapiens** [comment]
Hi @grandrea - I'm involved in setting up and maintaining the production service at fragpipe-analyst.org - the HTTPS certificates are currently valid, and I've tested connectivity from multiple parts of the world and found no issue. I _suspect_ this might be an issue with your local network.

If you are seeing an `DNS_PROBE_FINISHED_NXDOMAIN` error in your browser, this is because your DNS server cannot find the name fragpipe-analyst.org - this could be for various reasons. If you are using a DNS server managed by your organization, they may have some blocking / firewall rules in place that are preventing a lookup of fragpipe-analyst.org (and presumably many other domains) - your local IT support should be able to address it. You may also be able to work around it by configuring your computer to use a different DNS server (eg the [Google Public DNS](https://developers.google.com/speed/public-dns) at 8.8.8.8 and 8.8.4.4).

**Comment by grandrea** [comment]
Indeed it was as you said. Somehow blocked on my work network- I have managed to contact the admins to whitelist the site. Thanks
